[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$major.$minor.$patch$prerelease$version"
version_type = "semver"
version_provider = "npm"
update_changelog_on_bump = true
major_version_zero = true
